project:
    dataset: 'dataset'
    images: 'celeba10k'
    labels: 'labels.json'
    models: 'models'
    logs: 'logs'
    predictions: 'predictions'
    eda: 'eda'
dataset:
    samples_limit: null
    image:
        format: 'jpg'
        size: 64
        channels: 3
    labels:
        [
            'Male',
            'Eyeglasses',
            'Smiling',
            'Black_Hair',
            'Brown_Hair',
            'Blond_Hair',
            'Gray_Hair',
            'Bald',
        ]
architecture:
    filters: [16, 32, 64]
    latent_dim: 32
training:
    splits: [0.7, 0.2, 0.1]
    optimizer:
        name: 'Adam'
        learning_rate: 0.001
    loss: 'BinaryCrossentropy'
    evaluator: 'BinaryAccuracy'
    epochs: 300
    batch_size: 32
